"""
generate_sql_theory_migration.py
Generates a Supabase migration to UPDATE the html_body in notebook_content
for all 18 SQL days, injecting the rich theory content extracted from
the newly-generated public/sql/dayNN.html files.

This is needed because the live site serves content from Supabase (notebook_content table),
not from the static HTML files.
"""

import re
import os
from pathlib import Path

SQL_DIR = Path('public/sql')
OUT_PATH = Path('supabase/migrations/046_update_sql_theory.sql')

def extract_theory_html_from_day_html(html_path):
    """
    Extract the rich theory section from a generated day HTML file.
    The theory section is inside: <div style="border-left: 4px solid #4DB6AC; ...">
    """
    with open(html_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find the theory div — it's the content inside:
    # <div style="border-left: 4px solid #4DB6AC; ..."> ... </div>
    # But we need to extract the FULL nb-section that contains it
    # Actually, we want just what's inside the concept div
    
    # The structure in the generated HTML is:
    # <div class="nb-section" id="sec-1">
    #   <div class="nb-rich">
    #     <h2>...</h2>
    #     <div style="border-left: 4px solid #4DB6AC; ...">
    #       <b>🔍 Concept</b><br>
    #       [THEORY CONTENT HERE]
    #     </div>
    #   </div>
    # ...
    
    # Let's extract the inner content of the 4DB6AC div
    match = re.search(
        r'<div style="border-left: 4px solid #4DB6AC;[^"]*"[^>]*>(.*?)</div></div>',
        content,
        re.DOTALL
    )
    if not match:
        return None
    
    inner = match.group(1)
    # Remove the <b>🔍 Concept</b><br> header - it's already in the template
    inner = re.sub(r'\s*<b>🔍 Concept</b><br>\s*', '', inner)
    return inner.strip()

def extract_full_nb_section_1(html_path):
    """
    Extract the full first nb-section (sec-1) from the generated HTML.
    This contains the heading + theory content.
    """
    with open(html_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find sec-1 div start
    sec1_start = content.find('<div class="nb-section" id="sec-1">')
    if sec1_start == -1:
        return None
    
    # Find sec-1 end - next nb-section or checks section
    sec1_end = content.find('<div class="nb-section"', sec1_start + 10)
    if sec1_end == -1:
        return None
    
    return content[sec1_start:sec1_end].strip()

def extract_html_body_for_supabase(html_path):
    """
    Extract the entire notebook body content from the generated HTML file.
    This is everything between the notebook div and the sidebar.
    """
    with open(html_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find the main notebook content - starts after <main class="notebook"...>
    main_start = content.find('<main class="notebook"')
    if main_start == -1:
        return None
    
    # Find the content start (after the opening tag)
    content_start = content.find('>', main_start) + 1
    
    # Find the end before the sidebar
    main_end = content.find('</main>', content_start)
    if main_end == -1:
        return None
    
    # Extract just the sections (skip the nb-title which is rendered by the template)
    body = content[content_start:main_end].strip()
    
    # Remove the title section as it's already in the Next.js template
    nb_title_end = body.find('</div>\n<div class="nb-section"')
    if nb_title_end != -1:
        body = body[nb_title_end + len('</div>\n'):].strip()
    
    return body


print("Generating SQL theory update migration...\n")

updates = []

for day_num in range(1, 19):
    html_file = SQL_DIR / f'day{day_num:02d}.html'
    if not html_file.exists():
        print(f"  WARNING: {html_file} not found")
        continue
    
    html_body = extract_html_body_for_supabase(html_file)
    if not html_body:
        print(f"  WARNING: Could not extract body from day{day_num:02d}.html")
        continue
    
    # Escape single quotes for SQL
    escaped_body = html_body.replace("'", "''")
    
    day_id = f'sql-day{day_num:02d}'
    update_sql = f"""UPDATE public.notebook_content
SET html_body = '{escaped_body}'
WHERE day_id = '{day_id}';"""
    
    updates.append(update_sql)
    print(f"  Day {day_num:02d}: extracted {len(html_body)} chars")

# Write the migration file
migration_content = """-- ═══════════════════════════════════════════════════════════════
-- Migration 046: Update SQL notebook content with rich theory
-- Generated by generate_sql_theory_migration.py
-- Updates all 18 SQL days with full concept deep-dive content
-- ═══════════════════════════════════════════════════════════════

"""

migration_content += '\n\n'.join(updates)
migration_content += '\n'

with open(OUT_PATH, 'w', encoding='utf-8') as f:
    f.write(migration_content)

size_kb = OUT_PATH.stat().st_size / 1024
print(f"\nMigration written to {OUT_PATH} ({size_kb:.1f} KB)")
print(f"Total {len(updates)} day updates generated.")
print("\nNext steps:")
print("  1. Run this in Supabase SQL Editor, OR")
print("  2. Run: npx supabase db push  (if Supabase CLI is set up)")
