// ═══════════════════════════════════════════════════════════════════════
// MANO HINT SYSTEM v5 — Pre-computed Pedagogical Hints
// Reads data-hint-X attributes generated by Python script.
// Handles up to 5 progressive hints per question.
// ═══════════════════════════════════════════════════════════════════════

(function() {
  'use strict';

  var hintLevels = {};

  // ── Get code from editor ──
  function getCode(cellId) {
    if (typeof editors !== 'undefined' && editors[cellId]) {
      return editors[cellId].getValue();
    }
    var ta = document.querySelector('#' + cellId + ' textarea');
    return ta ? (ta.value || '') : '';
  }

  // ── Get error-specific hint ──
  function getErrorHint(cellId) {
    var outEl = document.querySelector('#' + cellId + ' .cell-output');
    if (!outEl || !outEl.classList.contains('error')) return null;
    var txt = outEl.textContent || '';
    if (txt.includes('SyntaxError')) return "🐛 You have a SyntaxError. Check for missing colons, brackets, or unmatched quotes.";
    if (txt.includes('NameError')) return "🐛 NameError — a variable or function name is misspelled or not defined yet.";
    if (txt.includes('TypeError')) return "🐛 TypeError — you're mixing types that don't work together (like string + number).";
    if (txt.includes('IndentationError')) return "🐛 IndentationError — use exactly 4 spaces after if, for, def, class.";
    if (txt.includes('IndexError')) return "🐛 IndexError — you're accessing an index that doesn't exist. Check len().";
    if (txt.includes('KeyError')) return "🐛 KeyError — that key isn't in the dictionary. Check spelling or use .get().";
    if (txt.includes('ValueError')) return "🐛 ValueError — the value isn't valid for this operation. Check your input.";
    if (txt.includes('ZeroDivisionError')) return "🐛 Can't divide by zero! Add a check before dividing.";
    if (txt.includes('AttributeError')) return "🐛 AttributeError — that method doesn't exist on this type. Check the data type.";
    return "🐛 Fix the error shown in red first, then try again.";
  }

  // ── Show / update hint popup ──
  function showHint(cellId) {
    var cell = document.getElementById(cellId);
    if (!cell) return;

    // Get question element and hints
    var prev = cell.previousElementSibling;
    if (!prev || (!prev.classList.contains('question') && !prev.classList.contains('interview'))) {
        return;
    }
    
    // Read pre-computed hints from attributes (up to 5)
    var hints = [];
    for (var i = 1; i <= 5; i++) {
        var h = prev.getAttribute('data-hint-' + i);
        if (h) hints.push(h);
    }
    
    // Fallback if no pre-computed hints found
    if (hints.length === 0) {
        hints = [
            "Read the question carefully and set up the necessary data.",
            "Identify the main Python concept and apply the appropriate operation.",
            "Make sure to print your final result and verify it matches the expectations."
        ];
    }
    
    var maxLevel = hints.length;

    // Initialize level
    if (!hintLevels[cellId]) hintLevels[cellId] = 0;
    
    // Check for error first
    var errHint = getErrorHint(cellId);
    
    // Determine level to show (only increment if we are not just showing an error for the first time)
    if (!errHint || hintLevels[cellId] > 0) {
        hintLevels[cellId]++;
    }
    
    var level = Math.min(Math.max(hintLevels[cellId], 1), maxLevel);

    // Determine what text to show
    var hintText = "";
    if (errHint && hintLevels[cellId] === 0) {
      hintText = errHint;
      level = 1; // display as 1
    } else if (errHint) {
      hintText = errHint + '\n\n' + hints[level - 1];
    } else {
      hintText = hints[level - 1];
    }

    // Find or create popup
    var popupId = 'hint-' + cellId;
    var popup = document.getElementById(popupId);

    if (popup) {
      // Update existing popup content (don't move it)
      var body = popup.querySelector('.mano-hint-body');
      body.style.opacity = '0';
      setTimeout(function() {
        body.innerHTML = hintText.replace(/\n/g, '<br>');
        popup.querySelector('.mano-hint-title').textContent = '💡 Hint (' + level + '/' + maxLevel + ')';
        body.style.opacity = '1';
        // Update footer
        var footer = popup.querySelector('.mano-hint-footer');
        if (level < maxLevel) {
          footer.innerHTML = '<button class="mano-hint-next" onclick="showHint(\'' + cellId + '\')">Next Hint →</button>';
        } else {
          footer.innerHTML = '<span class="mano-hint-final">No more hints — you can do this!</span>';
        }
      }, 120);
      return;
    }

    // Create new popup (as sibling after cell)
    popup = document.createElement('div');
    popup.id = popupId;
    popup.className = 'mano-hint-popup';

    popup.innerHTML =
      '<div class="mano-hint-header">' +
        '<span class="mano-hint-title">💡 Hint (' + level + '/' + maxLevel + ')</span>' +
        '<button class="mano-hint-close" onclick="closeHint(\'' + cellId + '\')">&times;</button>' +
      '</div>' +
      '<div class="mano-hint-body">' + hintText.replace(/\n/g, '<br>') + '</div>' +
      '<div class="mano-hint-footer">' +
        (level < maxLevel
          ? '<button class="mano-hint-next" onclick="showHint(\'' + cellId + '\')">Next Hint →</button>'
          : '<span class="mano-hint-final">No more hints — you can do this!</span>') +
      '</div>';

    // Insert after the cell
    cell.parentNode.insertBefore(popup, cell.nextSibling);

    // Animate in
    requestAnimationFrame(function() {
      requestAnimationFrame(function() {
        popup.classList.add('mano-hint-visible');
      });
    });
  }

  function closeHint(cellId) {
    var popupId = 'hint-' + cellId;
    var popup = document.getElementById(popupId);
    if (popup) {
      popup.classList.remove('mano-hint-visible');
      hintLevels[cellId] = 0;
      setTimeout(function() { if (popup.parentNode) popup.remove(); }, 200);
    }
  }

  // ── Inject hint buttons into question cells ──
  function injectHintButtons() {
    var cells = document.querySelectorAll('.code-cell');
    var count = 0;
    for (var i = 0; i < cells.length; i++) {
      var cell = cells[i];
      var prev = cell.previousElementSibling;
      if (!prev) continue;
      if (!prev.classList.contains('question') && !prev.classList.contains('interview')) continue;

      var actions = cell.querySelector('.cell-actions');
      if (!actions) continue;
      if (actions.querySelector('.hint-btn')) continue;

      var btn = document.createElement('button');
      btn.className = 'hint-btn';
      btn.type = 'button';
      btn.innerHTML = '💡 Hint';
      btn.setAttribute('data-cell', cell.id);
      btn.setAttribute('onclick', "showHint('" + cell.id + "')");
      actions.insertBefore(btn, actions.firstChild);
      count++;
    }
    console.log('ManoHint: ' + count + ' hint buttons injected');
  }

  // Make functions globally accessible (for onclick handlers)
  window.showHint = showHint;
  window.closeHint = closeHint;

  // Run after DOM is ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', injectHintButtons);
  } else {
    injectHintButtons();
  }
})();
