// ═══════════════════════════════════════════════════════════════════════
// MANO HINT SYSTEM v5 — Pre-computed Pedagogical Hints
// Reads data-hint-X attributes generated by Python script.
// Handles up to 5 progressive hints per question.
// ═══════════════════════════════════════════════════════════════════════

(function() {
  'use strict';

  var hintLevels = {};

  // ── Get code from editor ──
  function getCode(cellId) {
    if (typeof editors !== 'undefined' && editors[cellId]) {
      return editors[cellId].getValue();
    }
    var ta = document.querySelector('#' + cellId + ' textarea');
    return ta ? (ta.value || '') : '';
  }

  // ── Get error-specific hint (Smart randomized) ──
  function getErrorHint(cellId) {
    var outEl = document.querySelector('#' + cellId + ' .cell-output');
    if (!outEl || !outEl.classList.contains('error')) return null;
    var txt = outEl.textContent || '';
    
    // Pick a random hint from an array
    function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }

    // Smart regex extraction
    var nameMatch = txt.match(/NameError: name '([^']+)' is not defined/);
    var attrMatch = txt.match(/AttributeError: '([^']+)' object has no attribute '([^']+)'/);
    var keyMatch = txt.match(/KeyError: '([^']+)'/);
    var typeMatch = txt.match(/TypeError: (.*)/);

    if (txt.includes('SyntaxError')) {
      return pick([
        "🐛 SyntaxError: Python is confused by the grammar. Did you miss a colon `:` or a bracket `()`?",
        "🐛 SyntaxError spotted! Check the very end of your line. Are all quotes and parentheses closed?",
        "🐛 You have a SyntaxError. This usually means a typo in the Python structure. Double-check your commas and brackets.",
        "🐛 Oops, a SyntaxError. Python couldn't parse this. Look closely at the line it points to for missing syntax."
      ]);
    }
    if (nameMatch) {
      var n = nameMatch[1];
      return pick([
        "🐛 NameError: Python doesn't recognize `" + n + "`. Did you spell it correctly?",
        "🐛 NameError: You're trying to use `" + n + "`, but it hasn't been created yet. Check your spelling or define it first.",
        "🐛 Wait, what is `" + n + "`? Python threw a NameError because it cannot find a variable or function with that exact name."
      ]);
    }
    if (txt.includes('NameError')) {
      return pick([
        "🐛 NameError: You're calling a variable or function that doesn't exist yet.",
        "🐛 NameError: Check your spelling and capitalization! Python is case-sensitive."
      ]);
    }
    if (typeMatch) {
      var tInfo = typeMatch[1];
      return pick([
        "🐛 TypeError: You are mixing data types that don't belong together (like adding a string to a number).",
        "🐛 TypeError: " + tInfo + ". Make sure you are using the correct data type for this operation.",
        "🐛 TypeError! Are you trying to use a method on the wrong kind of object? Check what type of data you actually have using `type()`.",
        "🐛 TypeError: Python can't perform this action on this specific data type. You might need to convert it first using int(), str(), or list()."
      ]);
    }
    if (txt.includes('IndentationError')) {
      return pick([
        "🐛 IndentationError: Your spaces are misaligned. Remember to use exactly 4 spaces inside loops, functions, and if-statements.",
        "🐛 IndentationError! Python uses indentation to know what code belongs together. Check for extra or missing spaces at the start of the line.",
        "🐛 IndentationError: Make sure you aren't mixing tabs and spaces. Line up your code blocks perfectly."
      ]);
    }
    if (txt.includes('IndexError')) {
      return pick([
        "🐛 IndexError: You reached too far! You're trying to access an item at an index that doesn't exist in this list/tuple.",
        "🐛 IndexError: The list isn't that long. Remember, Python starts counting at 0. The last item is at `len(list) - 1`.",
        "🐛 IndexError spotted! If a list has 5 items, the highest index you can ask for is 4. Double-check your numbers."
      ]);
    }
    if (keyMatch) {
      var k = keyMatch[1];
      return pick([
        "🐛 KeyError: The dictionary does not contain the key `" + k + "`. Are you sure it's spelled right?",
        "🐛 KeyError for `" + k + "`. That key isn't in your dictionary. Maybe try using `.get()` to avoid errors?",
        "🐛 KeyError! You asked the dictionary for `" + k + "`, but it came up empty-handed."
      ]);
    }
    if (txt.includes('KeyError')) {
      return pick([
        "🐛 KeyError: You are trying to look up a key that doesn't exist in the dictionary.",
        "🐛 KeyError: Double-check the exact spelling of the key you are trying to access in the dict."
      ]);
    }
    if (txt.includes('ValueError')) {
      return pick([
        "🐛 ValueError: The function received the right *type* of data, but an inappropriate *value*. (Like trying to turn 'hello' into an integer).",
        "🐛 ValueError! The input you gave isn't valid for this specific operation. Look closely at the data you are passing in.",
        "🐛 ValueError: Python doesn't know how to process that specific value. Are you unpacking too many or too few variables?"
      ]);
    }
    if (txt.includes('ZeroDivisionError')) {
      return pick([
        "🐛 ZeroDivisionError: Mathematical impossibility! You cannot divide by zero.",
        "🐛 ZeroDivisionError: The denominator in your division operation turned out to be 0. Add an if-check to prevent this."
      ]);
    }
    if (attrMatch) {
      var obj = attrMatch[1];
      var attr = attrMatch[2];
      return pick([
        "🐛 AttributeError: A `" + obj + "` object doesn't have a method or property named `" + attr + "`.",
        "🐛 AttributeError: You are trying to use `." + attr + "()` but that doesn't work on a `" + obj + "`. Check the documentation or use `type()` to see what you actually have.",
        "🐛 AttributeError! `" + attr + "` is not a valid command for `" + obj + "` objects. Did you misspell the method name?"
      ]);
    }
    if (txt.includes('AttributeError')) {
      return pick([
        "🐛 AttributeError: You are trying to use a method that doesn't exist for this data type.",
        "🐛 AttributeError: Check what type of object you're working with. It doesn't support the `.something` you just tried to call."
      ]);
    }
    if (txt.includes('ModuleNotFoundError') || txt.includes('ImportError')) {
      return pick([
        "🐛 ModuleNotFoundError: Python can't find that library. Did you misspell the import statement?",
        "🐛 ImportError: That module or function isn't available. Check the spelling of what you are trying to import."
      ]);
    }
    
    // Generic fallback
    return pick([
      "🐛 An error occurred! Read the red text carefully—it usually tells you exactly which line caused the problem.",
      "🐛 Python threw an error. Look at the very bottom line of the error message to understand what went wrong.",
      "🐛 Fix the error shown in the output first, then try running the cell again."
    ]);
  }

  // ── Show / update hint popup ──
  function showHint(cellId) {
    var cell = document.getElementById(cellId);
    if (!cell) return;

    // Get question element and hints
    var prev = cell.previousElementSibling;
    if (!prev || (!prev.classList.contains('question') && !prev.classList.contains('interview'))) {
        return;
    }
    
    // Read pre-computed hints from attributes (up to 5)
    var hints = [];
    for (var i = 1; i <= 5; i++) {
        var h = prev.getAttribute('data-hint-' + i);
        if (h) hints.push(h);
    }
    
    // Fallback if no pre-computed hints found
    if (hints.length === 0) {
        hints = [
            "Read the question carefully and set up the necessary data.",
            "Identify the main Python concept and apply the appropriate operation.",
            "Make sure to print your final result and verify it matches the expectations."
        ];
    }
    
    var maxLevel = hints.length;

    // Initialize level
    if (!hintLevels[cellId]) hintLevels[cellId] = 0;
    
    // Check for error first
    var errHint = getErrorHint(cellId);
    
    // Determine level to show (only increment if we are not just showing an error for the first time)
    if (!errHint || hintLevels[cellId] > 0) {
        hintLevels[cellId]++;
    }
    
    var level = Math.min(Math.max(hintLevels[cellId], 1), maxLevel);

    // Voice narration removed

    // Determine what text to show
    var hintText = "";
    if (errHint && hintLevels[cellId] === 0) {
      hintText = errHint;
      level = 1; // display as 1
    } else if (errHint) {
      hintText = errHint + '\n\n' + hints[level - 1];
    } else {
      hintText = hints[level - 1];
    }

    // Find or create popup
    var popupId = 'hint-' + cellId;
    var popup = document.getElementById(popupId);

    if (popup) {
      // Update existing popup content (don't move it)
      var body = popup.querySelector('.mano-hint-body');
      body.style.opacity = '0';
      setTimeout(function() {
        body.innerHTML = hintText.replace(/\n/g, '<br>');
        popup.querySelector('.mano-hint-title').textContent = '💡 Hint (' + level + '/' + maxLevel + ')';
        body.style.opacity = '1';
        // Update footer
        var footer = popup.querySelector('.mano-hint-footer');
        if (level < maxLevel) {
          footer.innerHTML = '<button class="mano-hint-next" onclick="showHint(\'' + cellId + '\')">Next Hint →</button>';
        } else {
          footer.innerHTML = '<span class="mano-hint-final">No more hints — you can do this!</span>';
        }
      }, 120);
      return;
    }

    // Create new popup (as sibling after cell)
    popup = document.createElement('div');
    popup.id = popupId;
    popup.className = 'mano-hint-popup';

    popup.innerHTML =
      '<div class="mano-hint-header">' +
        '<span class="mano-hint-title">💡 Hint (' + level + '/' + maxLevel + ')</span>' +
        '<button class="mano-hint-close" onclick="closeHint(\'' + cellId + '\')">&times;</button>' +
      '</div>' +
      '<div class="mano-hint-body">' + hintText.replace(/\n/g, '<br>') + '</div>' +
      '<div class="mano-hint-footer">' +
        (level < maxLevel
          ? '<button class="mano-hint-next" onclick="showHint(\'' + cellId + '\')">Next Hint →</button>'
          : '<span class="mano-hint-final">No more hints — you can do this!</span>') +
      '</div>';

    // Insert after the cell
    cell.parentNode.insertBefore(popup, cell.nextSibling);

    // Animate in
    requestAnimationFrame(function() {
      requestAnimationFrame(function() {
        popup.classList.add('mano-hint-visible');
      });
    });
  }

  function closeHint(cellId) {
    var popupId = 'hint-' + cellId;
    var popup = document.getElementById(popupId);
    if (popup) {
      popup.classList.remove('mano-hint-visible');
      hintLevels[cellId] = 0;
      setTimeout(function() { if (popup.parentNode) popup.remove(); }, 200);
    }
  }

  // ── Inject hint buttons into question cells ──
  function injectHintButtons() {
    var cells = document.querySelectorAll('.code-cell');
    var count = 0;
    for (var i = 0; i < cells.length; i++) {
      var cell = cells[i];
      var prev = cell.previousElementSibling;
      if (!prev) continue;
      if (!prev.classList.contains('question') && !prev.classList.contains('interview')) continue;

      var actions = cell.querySelector('.cell-actions');
      if (!actions) continue;
      if (actions.querySelector('.hint-btn')) continue;

      var btn = document.createElement('button');
      btn.className = 'hint-btn';
      btn.type = 'button';
      btn.innerHTML = '💡 Hint';
      btn.setAttribute('data-cell', cell.id);
      btn.setAttribute('onclick', "showHint('" + cell.id + "')");
      actions.insertBefore(btn, actions.firstChild);
      count++;
    }
    console.log('ManoHint: ' + count + ' hint buttons injected');
  }

  // Make functions globally accessible (for onclick handlers)
  window.showHint = showHint;
  window.closeHint = closeHint;

  // Run after DOM is ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', injectHintButtons);
  } else {
    injectHintButtons();
  }
})();
