# MANODEMY SQL CURRICULUM — Auto-generated from manodemy_sql_curriculum.md
SQL_CURRICULUM = [
    {
        "day": 1,
        "title": 'Introduction to SQL & Databases',
        "db": 'retail.db',
        "emoji": '🗄️',
        "objective": 'Understand relational database management system (RDBMS) concepts, schemas, primary/foreign keys, and explore database structures.',
        "sections": [{
            "num": 1,
            "title": 'Introduction to SQL & Databases',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Introduction to SQL & Databases.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Write a query to retrieve only the <code>employee_id</code>, <code>first_name</code>, and <code>email</code> from the employees table.',
                "Write a query that displays each employee's full name as a single column called <code>full_name</code> (combine <code>first_name</code> and <code>last_name</code> with a space in between), and their salary with a 10% raise displayed as <code>projected_salary</code>.",
                "Write a query to retrieve all columns from the employees table but only show employees in <code>department_id</code> 3. (Use a WHERE clause — you'll explore this more deeply in Day 2.)",
                'Write a query that computes a column <code>annual_bonus</code> which is 5% of the <code>salary</code>, and show it alongside <code>first_name</code> and <code>salary</code>.',
                'Explain in a SQL comment (<code>--</code>) inside your query why the following query fails, and then fix it:\n``<code>sql\nSELECT salary * 1.15 AS new_salary\nFROM employees\nWHERE new_salary > 80000;\n</code>``\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is SQL and how is it different from other programming languages?',
            'What are the five sub-languages of SQL? Give one command example for each.',
            'What is the difference between <code>VARCHAR</code> and <code>CHAR</code> data types?',
            'What is a Primary Key? Can a table have multiple Primary Keys?',
            'What is the difference between a Primary Key and a Unique Key?',
            'What is a Foreign Key and what is its purpose in a relational database?',
            'Explain the SQL Order of Execution in detail.',
            "Why can't you use a column alias defined in SELECT inside the WHERE clause?",
            'What does <code>SELECT *</code> do, and when is it considered bad practice?',
            'What is the difference between <code>DECIMAL(10,2)</code> and <code>FLOAT</code>? When would you use each?',
            'What is a schema in the context of a database?',
            'What is the difference between a row and a column in a relational database?',
            'What is <code>DDL</code> vs <code>DML</code>? Give examples of each.',
            'What is a <code>NULL</code> value? How is <code>NULL</code> different from <code>0</code> or an empty string?',
            'Can a Primary Key column contain NULL values? Why or why not?',
            'What is the difference between <code>TRUNCATE</code> and <code>DELETE</code>? Which is DDL and which is DML?',
            'What is referential integrity? How does a Foreign Key enforce it?',
            'In SQL, what does the <code>AS</code> keyword do?',
            'What is the output of <code>SELECT 10 / 3</code> in SQL? How do you get a decimal result?',
            'What is the difference between <code>INT</code> and <code>BIGINT</code>?',
            'Can a table exist without a Primary Key? Is it a good practice?',
            'What is a composite key? Give a business example where you would use one.',
            'Explain what a relational database is. How is it different from a flat file (like a CSV)?',
            'What is <code>NOT NULL</code> constraint and when would you use it?',
            'You receive a table with 5 million rows. A colleague writes <code>SELECT *</code> in a production environment. What problem could this cause, and how would you advise them to write the query instead?\n\n---',
        ],
        "summary": 'Today you learned database fundamentals: what RDBMS is, how tables use columns and rows to represent entities, and the distinction between DDL/DQL/DML. Crucially, you learned the SQL Order of Execution (FROM -> JOIN -> WHERE -> GROUP BY -> HAVING -> SELECT -> DISTINCT -> ORDER BY -> LIMIT), which dictates how the engine compiles queries.'
    },
    {
        "day": 2,
        "title": 'Filtering Data with WHERE',
        "db": 'retail.db',
        "emoji": '🔍',
        "objective": 'Filter query results using conditional statements, logical operators, and value list checking.',
        "sections": [{
            "num": 1,
            "title": 'Filtering Data with WHERE',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Filtering Data with WHERE.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Retrieve all employees who earn more than ₹60,000 per month and work in <code>department_id</code> 4.',
                "Write a query to find all employees whose <code>job_title</code> is either 'Data Analyst', 'Business Analyst', or 'Data Scientist'.",
                'Find all employees hired between January 1, 2020 and December 31, 2022 whose salary is between ₹40,000 and ₹80,000. Use <code>BETWEEN</code> for both conditions.',
                'Find all employees who are NOT in <code>department_id</code> 1, 2, or 3, and whose salary is greater than ₹50,000. Use <code>NOT IN</code> and <code>AND</code>.',
                "A colleague wrote this query and it's returning wrong results. Identify the bug, explain why it's wrong using your knowledge of operator precedence, and fix it:\n``<code>sql\nSELECT * FROM employees\nWHERE department_id = 2 AND salary > 70000 OR is_active = TRUE;\n</code>``\n\n---",
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is the purpose of the <code>WHERE</code> clause and at which step does it execute in the SQL Order of Execution?',
            'What is the difference between <code>=</code> and <code>IN</code> operators? When would you prefer <code>IN</code>?',
            'Is <code>BETWEEN</code> inclusive or exclusive of its boundary values? Write an example.',
            'What happens when you use <code>NOT IN</code> with a list that contains a <code>NULL</code> value?',
            "Explain SQL's three-valued logic (TRUE, FALSE, UNKNOWN).",
            'What is operator precedence in SQL? Which has higher precedence: <code>AND</code> or <code>OR</code>?',
            'Write a query to find all employees who earn between ₹50,000 and ₹1,00,000.',
            'How would you write a case-insensitive text filter in PostgreSQL?',
            'What is the difference between <code><></code> and <code>!=</code> in SQL?',
            'Can you use aggregate functions (like SUM or COUNT) in a WHERE clause? Why or why not?',
            'Write a query that returns employees NOT in departments 4, 5, or 6.',
            'Why should you always use parentheses when combining AND and OR conditions?',
            'What is wrong with this query: <code>WHERE salary = NULL</code>? How do you correctly filter for NULLs?',
            'Write a query to find all employees hired in the year 2023.',
            'What does <code>WHERE salary > 50000 AND salary < 80000</code> mean? Can you rewrite it using BETWEEN?',
            'What is a Cartesian product? How does WHERE help avoid one?',
            'A query returns 0 rows but you expect results. What are 3 possible reasons related to the WHERE clause?',
            'How would you find all employees whose <code>email</code> column is NOT empty (but might be NULL or empty string)?',
            'What is the difference between filtering before a JOIN vs. filtering after a JOIN?',
            'Write a query to return employees who were hired after 2021 and earn more than the average salary. (Hint: use a subquery in WHERE — preview of Day 12.)',
            'What does <code>WHERE 1=1</code> do and where is it commonly used in applications?',
            'If a column has a <code>VARCHAR</code> data type, can you filter it with a numeric comparison like <code>WHERE employee_id > 1000</code>? What could go wrong?',
            'How do you filter a BOOLEAN column in SQL? Is <code>WHERE is_active = TRUE</code> the same as <code>WHERE is_active</code>?',
            'Explain why <code>WHERE salary NOT IN (SELECT salary FROM contractors WHERE salary IS NULL)</code> would return zero rows even if valid matches exist.',
            'A business analyst asks you to pull all employees who joined in Q1 2024. Write the query using two different approaches.\n\n---',
        ],
        "summary": 'Filtering is the core of SQL analysis. Today you mastered the WHERE clause, using comparison operators (=, !=, <, >), logical operators (AND, OR, NOT), range filters (BETWEEN), and list filters (IN). You also learned to handle operator precedence using parentheses.'
    },
    {
        "day": 3,
        "title": 'Pattern Matching & NULL Handling',
        "db": 'retail.db',
        "emoji": '📝',
        "objective": 'Perform text search using wildcards and understand how to handle missing (NULL) values correctly.',
        "sections": [{
            "num": 1,
            "title": 'Pattern Matching & NULL Handling',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Pattern Matching & NULL Handling.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Find all employees whose <code>email</code> ends with <code>@manodemy.com</code>. Use the <code>LIKE</code> operator.',
                "Find all employees whose <code>job_title</code> contains the word 'analyst' (case-insensitive) but does NOT start with 'Senior'. Use <code>ILIKE</code> (or <code>LOWER</code> + <code>LIKE</code>) and <code>NOT LIKE</code>.",
                'Find all employees who have no manager assigned (<code>manager_id</code> is NULL). These are the top-level employees. Display their <code>first_name</code>, <code>last_name</code>, and <code>job_title</code>.',
                "Write a query that displays each employee's <code>first_name</code>, <code>salary</code>, and <code>total_compensation</code>. <code>total_compensation</code> = salary + commission. Employees with a NULL commission should have it treated as 0. Use <code>COALESCE</code>.",
                'Write a query that calculates <code>revenue_per_unit</code> for products in a <code>sales</code> table (columns: <code>product_id</code>, <code>revenue</code>, <code>units_sold</code>). Ensure the query does not crash when <code>units_sold</code> is 0. Use <code>NULLIF</code>. Display <code>product_id</code>, <code>revenue</code>, <code>units_sold</code>, and <code>revenue_per_unit</code>.\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is NULL in SQL? Is it the same as 0 or an empty string?',
            'Why does <code>WHERE column = NULL</code> return 0 rows? What is the correct syntax?',
            'What is the correct operator to check if a value is NULL? Give an example.',
            'What does <code>COALESCE</code> do? Write an example where it is used in a salary calculation.',
            'What is <code>NULLIF</code>? Explain its most common real-world use case.',
            'How do <code>NULL</code> values interact with aggregate functions like <code>SUM</code> and <code>AVG</code>?',
            'What is the difference between <code>COUNT(*)</code> and <code>COUNT(column_name)</code>?',
            'How do <code>NULL</code> values sort in ascending vs. descending <code>ORDER BY</code>?',
            'Explain the <code>LIKE</code> operator. What is the difference between <code>%</code> and <code>_</code> wildcards?',
            "What is a leading wildcard (<code>LIKE '%text'</code>) and why should it be avoided on large tables?",
            'What is <code>ILIKE</code> and which database supports it natively?',
            "If you need a case-insensitive LIKE search in a database that doesn't support ILIKE, how do you achieve it?",
            'What does <code>NULL AND TRUE</code> evaluate to in SQL? What about <code>NULL OR TRUE</code>? Explain three-valued logic.',
            'A developer wrote <code>WHERE commission != 0</code> to find employees without commission. What is wrong with this? How do you fix it?',
            'How does NULL propagate in arithmetic? What is <code>5 + NULL</code>?',
            'What is the result of <code>COALESCE(NULL, NULL, NULL)</code>?',
            'What is <code>NULLIF(10, 10)</code>? What is <code>NULLIF(10, 5)</code>?',
            "Write a query that finds all employees whose <code>first_name</code> starts with 'J' and has exactly 5 characters.",
            'Why might a <code>NOT IN</code> query return 0 rows when the list contains a NULL? Explain the mechanism.',
            'How would you replace NULL values in a column with a specific string for reporting purposes?',
            'You have a <code>revenue</code> and <code>cost</code> column. Some cost values are NULL. Write a query that safely computes profit as <code>revenue - cost</code>, treating NULL cost as 0.',
            'What is the difference between <code>IS NOT NULL</code> and <code><> NULL</code>?',
            'In what real business scenarios would a column legitimately contain NULL values?',
            'Write a query to identify columns that might have data quality issues (e.g., NULL values) in a table.',
            'A report is showing incorrect averages. You suspect NULL values are skewing the result. How do you investigate and fix it?\n\n---',
        ],
        "summary": 'Mastering partial matching and missing values is essential. Today you learned to perform search queries using LIKE/ILIKE wildcards (% and _), check for NULLs using IS NULL/IS NOT NULL, fallback to defaults using COALESCE, and prevent division-by-zero errors using NULLIF.'
    },
    {
        "day": 4,
        "title": 'Sorting & Limiting Results',
        "db": 'retail.db',
        "emoji": '📈',
        "objective": 'Control the display order of rows and restrict output size for pagination or top-N analysis.',
        "sections": [{
            "num": 1,
            "title": 'Sorting & Limiting Results',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Sorting & Limiting Results.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Write a query to find the 10 most recently hired employees. Display their <code>first_name</code>, <code>last_name</code>, and <code>hire_date</code> in order of most recent first.',
                'Write a pagination query to display employees sorted by <code>last_name</code> alphabetically. Return rows 21 through 30 (page 3 with a page size of 10). Use <code>LIMIT</code> and <code>OFFSET</code>.',
                'Write a query to find all unique <code>job_title</code> values in the company, sorted alphabetically. How many unique job titles are there? (Write two queries — one for the list, one for the count.)',
                'Find the 3rd highest salary in the company without using any window functions. Use <code>LIMIT</code> and <code>OFFSET</code>. Think carefully about how to handle ties.',
                'A report needs the bottom 5 earners in <code>department_id</code> 2, sorted by salary ascending then by <code>hire_date</code> ascending (longest-serving first among equal salaries). Write the query.\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'At which step does <code>ORDER BY</code> execute in the SQL Order of Execution?',
            'Why can you reference a column alias from <code>SELECT</code> in <code>ORDER BY</code> but not in <code>WHERE</code>?',
            'What is the default sort order of <code>ORDER BY</code>?',
            'What does <code>ORDER BY department_id ASC, salary DESC</code> do?',
            'Write a query to get the top 3 earners in the company.',
            'What is <code>OFFSET</code> and how does it enable pagination?',
            'What happens if you write <code>LIMIT 10</code> without <code>ORDER BY</code>?',
            'What is the difference between <code>LIMIT</code> (MySQL/PostgreSQL) and <code>FETCH FIRST n ROWS ONLY</code> (SQL Standard)?',
            'What does <code>DISTINCT</code> do? At which step in execution order does it run?',
            'Why is using <code>DISTINCT</code> to fix duplicate results from a JOIN considered bad practice?',
            'Write a query to count the number of unique departments in the employees table.',
            'How would you find the 2nd highest salary in a table? Show using LIMIT/OFFSET.',
            'What is <code>ORDER BY RANDOM()</code> and what is it used for?',
            'If a table has 1000 rows and you write <code>LIMIT 10 OFFSET 990</code>, how many rows are returned?',
            'Can you use <code>ORDER BY</code> without a <code>SELECT</code> clause? Explain.',
            'What is the difference between <code>DISTINCT</code> and <code>GROUP BY</code> for deduplication?',
            'How does <code>ORDER BY</code> handle NULL values by default?',
            'Write a query to get rows 51-60 from a products table ordered by price.',
            'What is the problem with offset-based pagination on large tables? (Performance consideration.)',
            'Can you sort by a column that is not in the SELECT list?',
            'How would you find the most recent hire date in each department? (Preview of GROUP BY.)',
            'What does <code>SELECT DISTINCT department_id, job_title</code> return compared to <code>SELECT DISTINCT department_id</code>?',
            'A business user asks for "the top 10 products" — what clarifying questions should you ask before writing the query?',
            'How would you return the first row of each department sorted by salary? (Preview of Window Functions.)',
            'Write a query that finds employees hired in 2023, sorted from lowest to highest salary, showing only the 5th and 6th employees.\n\n---',
        ],
        "summary": 'Sorting and limiting are vital for reporting and pagination. Today you learned to sort query results using ORDER BY (including multi-column and alias-based sorting), paginate results using LIMIT and OFFSET, deduplicate rows using DISTINCT, and retrieve random records.'
    },
    {
        "day": 5,
        "title": 'Aggregate Functions',
        "db": 'retail.db',
        "emoji": '📊',
        "objective": 'Calculate summary metrics like counts, sums, averages, minimums, and maximums across datasets.',
        "sections": [{
            "num": 1,
            "title": 'Aggregate Functions',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Aggregate Functions.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Write a single query that returns the total number of employees, total payroll (SUM of salary), average salary, highest salary, and lowest salary.',
                "Find the number of employees who have a commission (commission IS NOT NULL) vs. those who don't. Use two separate <code>COUNT</code> expressions in a single query.",
                'Write a query to find the average salary of only **active** employees (<code>is_active = TRUE</code>). Round the result to 2 decimal places.',
                'Write a query to find the number of employees hired each year. (Hint: use <code>EXTRACT</code> or <code>DATE_PART</code> to extract the year from <code>hire_date</code> — preview of Day 17, but try it.)',
                'The HR team reports that the average commission is ₹3,500. You notice that 40% of employees have NULL commission. Write two queries: one that shows the biased average (ignoring NULLs) and one that shows the true average (treating NULL as 0). Explain the difference in a SQL comment.\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is an aggregate function? Name the five core aggregate functions in SQL.',
            'What is the difference between <code>COUNT(*)</code> and <code>COUNT(column_name)</code>?',
            'How does <code>AVG</code> handle NULL values? Give an example where this could cause a misleading result.',
            'Can you use aggregate functions in a <code>WHERE</code> clause? Why not?',
            'What is <code>COUNT(DISTINCT column)</code>? Write an example.',
            'What does <code>MIN</code> and <code>MAX</code> return for a text/VARCHAR column?',
            'Write a query to find the total payroll cost for department_id = 5.',
            'What is the difference between <code>SUM(salary)</code> and <code>COUNT(*) * AVG(salary)</code>? Will they always be equal?',
            'How would you compute the standard deviation of salaries in SQL?',
            'What is <code>STRING_AGG</code>? Give a practical business example.',
            'If you run an aggregate function with no <code>GROUP BY</code>, what does it return?',
            'How do you round an aggregate result to 2 decimal places?',
            'Write a query to find the salary range (difference between highest and lowest salary) in the company.',
            'What is the difference between <code>SUM</code> and <code>COUNT</code>?',
            'Can <code>MIN</code> and <code>MAX</code> work on date columns? What do they return?',
            'Write a query to find the average salary but only for employees hired after 2020.',
            'What happens when you mix aggregate and non-aggregate columns in SELECT without GROUP BY?',
            'What does <code>COUNT(*) FILTER (WHERE is_active = TRUE)</code> do? (PostgreSQL)',
            'How would you find the number of distinct job titles in the company?',
            'What is the difference between <code>AVG(COALESCE(commission, 0))</code> and <code>COALESCE(AVG(commission), 0)</code>?',
            'A business question: "What percentage of our employees earn above ₹70,000?" Write the SQL query.',
            "How would you calculate the median salary in SQL? (SQL doesn't have a built-in MEDIAN in all databases.)",
            'What does <code>MAX(hire_date)</code> return — the first hire or the last hire?',
            'Write a query to find departments with more than 10 employees. (Preview of HAVING.)',
            "You're auditing data quality. Write a query that shows, for each column in the employees table, the count of NULL values.\n\n---",
        ],
        "summary": 'Aggregations allow summarizing large datasets into key business metrics. Today you mastered the five core functions: COUNT, SUM, AVG, MIN, and MAX, along with the ROUND function for formatting, and string aggregation using STRING_AGG/GROUP_CONCAT.'
    },
    {
        "day": 6,
        "title": 'GROUP BY & HAVING',
        "db": 'retail.db',
        "emoji": '🗃️',
        "objective": 'Group data rows by matching column values and filter aggregated summaries using HAVING.',
        "sections": [{
            "num": 1,
            "title": 'GROUP BY & HAVING',
            "subtitle": 'Concept Review',
            "theory": 'Learn about GROUP BY & HAVING.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Write a query that shows the number of employees and average salary for each <code>department_id</code>. Order results by average salary descending.',
                'Find all departments where the average salary exceeds ₹65,000 AND the headcount is at least 5. Use <code>GROUP BY</code> with <code>HAVING</code>.',
                'Write a query that shows, for each <code>job_title</code>, the number of employees with that title, the minimum salary, and the maximum salary. Only include job titles that appear more than 3 times.',
                'Find the year with the most employee hires. Show the <code>hire_year</code> and the count of hires for that year only. (You need to GROUP BY the extracted year from <code>hire_date</code>.)',
                'A manager asks: "Show me departments where more than 20% of employees are inactive." Write the query using <code>GROUP BY</code> and <code>HAVING</code> with aggregate expressions.\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What does <code>GROUP BY</code> do in SQL? At which execution step does it run?',
            'Explain the Golden Rule of <code>GROUP BY</code> — which columns must be in GROUP BY?',
            'What is <code>HAVING</code> and how is it different from <code>WHERE</code>?',
            'Can you use <code>WHERE</code> to filter based on the result of an aggregate function? Why not?',
            'Can you use <code>HAVING</code> without <code>GROUP BY</code>?',
            'What is the execution order of WHERE, GROUP BY, and HAVING?',
            'Write a query to find the department with the highest average salary.',
            'What is the difference between grouping by one column vs. two columns?',
            'Can you use a column alias from SELECT in a HAVING clause?',
            'Write a query to find all job titles that appear more than 5 times.',
            'What does <code>GROUP BY ROLLUP</code> do?',
            'If a GROUP BY query returns 0 rows, what are the likely causes?',
            'Write a query to find the total payroll per department.',
            'How do NULLs behave in GROUP BY? Are all NULLs grouped together?',
            'What is the difference between <code>HAVING COUNT(*) > 5</code> and <code>WHERE count > 5</code>?',
            'How would you find departments with the highest and lowest headcount in one query?',
            'Write a query to show the number of employees hired per month of 2023.',
            'Can you GROUP BY a column that is not in the SELECT list?',
            'Write a query that finds, per department, the difference between the max and min salary.',
            'Explain this query: <code>SELECT department_id, AVG(salary) FROM employees GROUP BY 1</code> — what does GROUP BY 1 mean?',
            'A query uses <code>GROUP BY</code> on 3 columns. How many groups are possible at maximum?',
            'What is <code>GROUP BY CUBE</code>?',
            'You have a query that counts orders per customer. How do you find customers with exactly 0 orders? (Preview of JOINs.)',
            'Write a query to find the most common job title in the company.',
            'Business question: "Which departments have a salary spread (max - min) greater than ₹40,000?" Write the SQL.\n\n---',
        ],
        "summary": 'Grouping allows category-level breakdowns. Today you mastered the GROUP BY clause to aggregate data across segments, and the HAVING clause to filter aggregated groups. You also studied the difference between WHERE (row-level filtering before group) and HAVING (group-level filtering after group).'
    },
    {
        "day": 7,
        "title": 'Data Types, Casting & Expressions',
        "db": 'retail.db',
        "emoji": '➕',
        "objective": 'Learn explicit data type casting, execute arithmetic expressions, and handle date/time values.',
        "sections": [{
            "num": 1,
            "title": 'Data Types, Casting & Expressions',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Data Types, Casting & Expressions.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Write a query that casts <code>text_salary</code> to <code>DECIMAL(10,2)</code> and <code>text_hire_date</code> to <code>DATE</code>. Display both alongside the original text columns.',
                'Demonstrate the integer division problem: write a query that incorrectly computes <code>salary / workdays</code> (both integers), then fix it using explicit casting.',
                'Create a query that concatenates <code>first_name</code> and <code>last_name</code> from the employees table as <code>full_name</code>, converts it to uppercase, and shows the length of the resulting full name as <code>name_length</code>.',
                'You have a <code>financial_data</code> table with <code>amount FLOAT</code>. Show why using <code>FLOAT</code> for currency comparison is problematic by writing a query that compares a computed float sum to an expected value. Then redesign the column type in a CREATE TABLE statement using <code>DECIMAL</code>.',
                'Write a query that safely converts text values in a <code>category_id</code> column to integers using <code>CASE WHEN</code> and a regular expression check (to avoid cast errors). Return NULL for non-numeric values.\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is the difference between <code>CAST</code> and <code>::</code> in PostgreSQL?',
            'What is the difference between <code>DECIMAL</code> and <code>FLOAT</code>? Why should you never use <code>FLOAT</code> for financial data?',
            'What is integer division? How do you force decimal division in SQL?',
            'What is the difference between <code>CHAR(n)</code>, <code>VARCHAR(n)</code>, and <code>TEXT</code>?',
            'What is <code>TIMESTAMP</code> vs. <code>TIMESTAMPTZ</code>? When would you use each?',
            'What is implicit casting? Give an example where it might cause unexpected behavior.',
            'What is <code>TRY_CAST</code> in SQL Server and what problem does it solve?',
            'What is <code>DECIMAL(10, 2)</code>? What is the maximum value it can store?',
            'Why does <code>SELECT 0.1 + 0.2 = 0.3</code> return FALSE in SQL?',
            'What is an <code>INTERVAL</code> data type used for?',
            'How do you convert a boolean to an integer in SQL?',
            'What is the difference between <code>UPPER()</code> and <code>LOWER()</code>? Give a real use case.',
            'Write a query that displays the annual salary for each employee from a monthly salary column.',
            'What does <code>TRIM()</code> do? What are <code>LTRIM()</code> and <code>RTRIM()</code>?',
            'How do you concatenate two string columns in SQL? Does the syntax differ across databases?',
            'What is <code>LENGTH()</code> vs. <code>CHAR_LENGTH()</code>?',
            'A column was imported as VARCHAR but needs to be used in arithmetic. How do you handle this?',
            'Explain data type precedence in SQL expressions (e.g., INT + DECIMAL = ?).',
            'What is the <code>COERCE</code> concept in database systems?',
            "You receive a text column with values like '₹75,000.00'. Write a query to convert it to a usable numeric value.",
            'What is the BOOLEAN data type and which values does it accept?',
            'What is the maximum number of characters a <code>VARCHAR(255)</code> column can store?',
            "In SQL, what is the difference between the string '5' and the number 5?",
            'Why would a JOIN fail silently (return fewer rows than expected) when joining an INT column to a VARCHAR column?',
            'A data pipeline imports all columns as TEXT. List 5 data types you would cast each column to and explain why.\n\n---',
        ],
        "summary": 'Data type control is vital for data integrity. Today you learned to perform explicit type conversions using CAST, execute safe arithmetic, and parse date and time components in queries.'
    },
    {
        "day": 8,
        "title": 'CASE WHEN (Conditional Logic)',
        "db": 'retail.db',
        "emoji": '🔀',
        "objective": 'Implement conditional if-then-else logic using CASE WHEN expressions inside queries.',
        "sections": [{
            "num": 1,
            "title": 'CASE WHEN (Conditional Logic)',
            "subtitle": 'Concept Review',
            "theory": 'Learn about CASE WHEN (Conditional Logic).',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                "Write a query that classifies each employee into a salary band: 'Top Earner' (>₹90,000), 'Senior' (₹60,001–₹90,000), 'Mid' (₹35,001–₹60,000), 'Junior' (≤₹35,000). Display <code>first_name</code>, <code>salary</code>, and <code>salary_band</code>.",
                'Write a query using **conditional aggregation** that shows, in a SINGLE row: total employees, count of Engineering employees (dept 1), count of Sales employees (dept 2), count of HR employees (dept 3), and total payroll.',
                'The company wants to give raises: Engineering gets 15%, Sales gets 10%, all others get 5%. Write a query that shows <code>first_name</code>, <code>current_salary</code>, and <code>new_salary</code> (using CASE WHEN on department_id).',
                'Write a query that sorts employees by a custom priority order: CEOs first, then Directors, then Managers, then all other job titles alphabetically.',
                "Using CASE WHEN without GROUP BY, write a query that shows for each employee a column <code>tenure_category</code>: 'Veteran' (hired before 2018), 'Experienced' (2018-2021), 'New Hire' (after 2021). Then, write a second query using GROUP BY on this CASE WHEN expression to count employees in each category.\n\n---",
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is <code>CASE WHEN</code> in SQL and what is its purpose?',
            'What is the difference between Simple CASE and Searched CASE?',
            'In what order does CASE WHEN evaluate its conditions? Why does this matter?',
            'What happens if no condition matches and there is no ELSE clause?',
            'Can CASE WHEN return different data types in different WHEN branches?',
            "Write a query that uses CASE WHEN to create a 'Pay Grade' column (A, B, C, D) based on salary ranges.",
            'What is conditional aggregation? Write an example.',
            'How do you use CASE WHEN inside an aggregate function?',
            'Can CASE WHEN be used in the WHERE clause? Give an example.',
            'Can CASE WHEN be nested? Show an example.',
            'What is <code>IIF</code> and in which database is it supported?',
            'How would you use CASE WHEN to implement a custom sort order?',
            'How is CASE WHEN used to "pivot" data (transform rows into columns)?',
            'Write a query that counts male and female employees in separate columns using conditional aggregation.',
            'What is the output data type of a CASE WHEN expression with mixed THEN data types?',
            'Can CASE WHEN handle NULL values? Write an example.',
            'How do you use CASE WHEN to classify dates (e.g., Q1, Q2, Q3, Q4)?',
            'What is the performance difference between multiple WHERE conditions vs. CASE WHEN?',
            "Write a query that gives a 20% discount to category 'Electronics', 10% to 'Clothing', and 0% to others in an orders table.",
            'Explain why <code>COUNT(CASE WHEN condition THEN 1 END)</code> works as a conditional count.',
            'What is the difference between <code>COUNT(CASE WHEN ... THEN 1 END)</code> and <code>SUM(CASE WHEN ... THEN 1 ELSE 0 END)</code>?',
            "A business wants a report showing the salary-to-bonus ratio categorized as 'Generous' (>20%), 'Standard' (10-20%), and 'Low' (<10%). Write the query.",
            'How do you use CASE WHEN to replace IIF across all databases?',
            "Write a query to flag orders as 'Late' if shipped more than 7 days after order date, 'On Time' otherwise.",
            "You have a column <code>status_code</code> with values 1, 2, 3. Map them to 'Pending', 'Active', 'Closed' using CASE WHEN. Which type of CASE is most appropriate?\n\n---",
        ],
        "summary": 'Conditional logic makes queries dynamic. Today you mastered the CASE WHEN expression to build conditional if-then-else logic directly inside SELECT statements, mapping raw values to analytical cohorts.'
    },
    {
        "day": 9,
        "title": 'Understanding Relationships & INNER JOIN',
        "db": 'company.db',
        "emoji": '🔗',
        "objective": 'Combine columns from multiple tables using relationship keys and INNER JOIN constraints.',
        "sections": [{
            "num": 1,
            "title": 'Understanding Relationships & INNER JOIN',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Understanding Relationships & INNER JOIN.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                "Write a query that shows each employee's <code>first_name</code>, <code>last_name</code>, <code>salary</code>, and their <code>department_name</code>. Use INNER JOIN to link employees to departments.",
                'Extend Challenge 1 to include a third table: <code>job_titles</code>. Join the employees table to <code>job_titles</code> on <code>job_title_id</code>. Display <code>first_name</code>, <code>department_name</code>, and <code>title_name</code>.',
                "Write a query to find all employees in the 'Sales' department with a salary above ₹60,000. Use INNER JOIN and filter with WHERE.",
                "Using a non-equi JOIN, write a query that maps each employee's salary to a salary grade from the <code>salary_grades</code> table (columns: grade, min_salary, max_salary). Display <code>first_name</code>, <code>salary</code>, and <code>grade</code>.",
                'Count how many employees are in each department. Display <code>department_name</code> and <code>employee_count</code>. Sort by <code>employee_count</code> descending. (Use INNER JOIN + GROUP BY.)\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is a JOIN in SQL and why is it necessary?',
            'What is an INNER JOIN? What rows does it exclude?',
            'At which step of SQL Order of Execution does JOIN run?',
            'What is a table alias and why is it recommended?',
            'What is the difference between <code>JOIN</code> and <code>INNER JOIN</code>? Are they the same?',
            'What happens when you join on a column that has NULL values?',
            'Write a query that joins employees to departments and shows only the department name and headcount.',
            'What is a composite join? Give a real-world example.',
            'What is a non-equi join? Give a business example.',
            'How many rows can an INNER JOIN produce between two tables with 100 and 10 rows?',
            'What is a foreign key and how does it relate to JOIN operations?',
            'Write a query to join 3 tables: employees, departments, and office_locations.',
            'What is the difference between filtering with WHERE and filtering with ON in a JOIN?',
            'Can you JOIN a table to itself? Is that an INNER JOIN?',
            'What is referential integrity and what happens to JOINs when it is violated?',
            'What is a Cartesian product and how does it happen accidentally in JOINs?',
            "Write a query to find all employees whose department is located in 'Mumbai'.",
            'Can you JOIN on a non-key column? What are the risks?',
            'What is the visual representation (Venn diagram) of INNER JOIN?',
            'What is the difference between a fact table and a dimension table in data warehouse context?',
            'Write a query to find managers (employees whose employee_id appears as manager_id for someone else). (Preview of self join.)',
            'What are the performance implications of JOIN on large tables?',
            'When is it appropriate to use a JOIN vs. a subquery?',
            'What index would you create to optimize an INNER JOIN query?',
            'A business asks: "List all employees with their team lead names." Given one employees table that stores manager relationships, how would you approach this?\n\n---',
        ],
        "summary": 'Relational databases derive their power from connections. Today you mastered database relationships (PK-FK constraints) and combined multiple tables horizontally using INNER JOIN.'
    },
    {
        "day": 10,
        "title": 'LEFT, RIGHT & FULL OUTER JOIN',
        "db": 'company.db',
        "emoji": '🔄',
        "objective": 'Understand LEFT, RIGHT, and FULL OUTER JOINs to preserve unmatched rows from tables.',
        "sections": [{
            "num": 1,
            "title": 'LEFT, RIGHT & FULL OUTER JOIN',
            "subtitle": 'Concept Review',
            "theory": 'Learn about LEFT, RIGHT & FULL OUTER JOIN.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Write a query to list ALL employees, including those without a department. Show <code>first_name</code>, <code>last_name</code>, and <code>department_name</code> (show NULL for employees with no department).',
                'Write a query to find all employees who are NOT assigned to any project. Use LEFT JOIN on <code>employee_projects</code> and filter for NULLs.',
                'Write a query to find all departments that have NO employees. Use the appropriate JOIN type and anti-join pattern.',
                'Write a query using FULL OUTER JOIN between <code>employees</code> and <code>departments</code> to show all unmatched records from both sides. Show <code>first_name</code> and <code>department_name</code>, filtering to only show rows where either side is NULL.',
                "A manager wants to see all employees and, if they have a manager, show the manager's name. If they have no manager (top-level employees), show 'No Manager' instead of NULL. Use LEFT JOIN (self-join preview) and COALESCE.\n\n---",
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is the difference between INNER JOIN and LEFT JOIN?',
            'What is a LEFT JOIN? What happens to unmatched rows from the left table?',
            'What is a RIGHT JOIN? Can it always be rewritten as a LEFT JOIN?',
            'What is FULL OUTER JOIN? Give a real-world use case.',
            'Does MySQL support FULL OUTER JOIN? How do you simulate it?',
            'Write a query to find all employees without a department.',
            'What is the Anti-Join pattern? Write an example.',
            'What is the difference between <code>WHERE d.department_id IS NULL</code> (after LEFT JOIN) and <code>WHERE d.department_id IS NOT NULL</code>?',
            'Can you use a WHERE clause on a LEFT JOIN without converting it to an INNER JOIN?',
            'What does filtering the RIGHT table in the ON clause vs. the WHERE clause do in a LEFT JOIN?',
            'Write a query to show all departments with their employee count, including departments with 0 employees.',
            'What is a NULL row in the context of an OUTER JOIN?',
            'What is the visual Venn diagram representation of LEFT JOIN with the IS NULL filter?',
            'How do multiple LEFT JOINs work when one of the intermediate joins produces a NULL?',
            'Write a query to compare data between two tables (find rows in table A not in table B).',
            'What is the difference between NOT IN, NOT EXISTS, and LEFT JOIN anti-join?',
            'When would you use FULL OUTER JOIN in a real data engineering project?',
            'What is the order of multiple JOINs in SQL? Is it left-to-right?',
            'Can you OUTER JOIN on a non-key column?',
            'Write a query to find all products that have never been ordered.',
            'Explain why this query is wrong for finding employees without a department: <code>SELECT * FROM employees WHERE department_id IS NULL</code>.',
            'What happens to aggregate functions when LEFT JOIN produces NULL rows?',
            'How do you count employees per department including departments with 0 employees?',
            'What is the difference between <code>JOIN ... ON condition AND other_condition</code> vs. <code>JOIN ... ON condition WHERE other_condition</code>?',
            'A data quality report needs to identify orphaned records (rows in a child table with no matching parent). Write the query pattern.\n\n---',
        ],
        "summary": 'Preserving unmatched data is key for detecting anomalies or optional relations. Today you mastered LEFT, RIGHT, and FULL OUTER JOINs, and simulated unsupported joins using UNION.'
    },
    {
        "day": 11,
        "title": 'SELF JOIN & Multi-Table Queries',
        "db": 'company.db',
        "emoji": '👥',
        "objective": 'Join a table to itself using SELF JOINs and construct multi-table query chains.',
        "sections": [{
            "num": 1,
            "title": 'SELF JOIN & Multi-Table Queries',
            "subtitle": 'Concept Review',
            "theory": 'Learn about SELF JOIN & Multi-Table Queries.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                "Write a SELF JOIN query to display each employee's name and their direct manager's name. Employees with no manager should show 'No Manager' (use COALESCE).",
                "Find all employees who earn MORE than their direct manager. Show the employee's name, their salary, the manager's name, and the manager's salary.",
                'Using SELF JOIN, find all pairs of employees who work in the same department but are different people. Ensure each pair appears only once (A,B not B,A).',
                'Write a multi-table query joining <code>orders</code>, <code>customers</code>, <code>order_items</code>, and <code>products</code> to show the top 5 most valuable orders (total revenue = sum of quantity × unit_price per order).',
                'Write a CROSS JOIN query to generate all possible product-store combinations from a <code>products</code> table and a <code>stores</code> table. This would be used to populate a full sales matrix (even showing 0-sale combinations).\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is a SELF JOIN? Give a real-world use case.',
            'Why do you need to alias the same table twice in a SELF JOIN?',
            "Write a query to find all employees and their manager's name from a single employees table.",
            'Why would you use LEFT JOIN instead of INNER JOIN in a self-referencing query?',
            'Write a query to find employees who earn more than their manager.',
            'How do you prevent duplicate pairs in a peer-finding SELF JOIN query?',
            'What is a CROSS JOIN? When is it actually useful?',
            'What is the result size of a CROSS JOIN between a 100-row and 50-row table?',
            'What is a LATERAL JOIN in PostgreSQL?',
            'How do you join 4 tables efficiently? What is the recommended approach?',
            'What is the risk of having too many JOINs in a single query?',
            'What is a hierarchical relationship? Give 3 business examples.',
            'How would you find the second-level managers (managers of managers) using SELF JOIN?',
            'What is the difference between a CROSS JOIN and a full Cartesian product from an accidental missing ON clause?',
            'Write a query to find all departments that have employees who earn more than the department average.',
            'What is a "fan-out" problem in multi-table JOIN queries and how does it affect aggregates?',
            'How do you debug a query that returns more rows than expected from a multi-table JOIN?',
            'What is the difference between a SELF JOIN and a recursive CTE (preview of Day 13)?',
            'Explain how CROSS JOIN could be used to generate a report grid.',
            'In a star schema, how do fact tables and dimension tables typically join?',
            'Write a query to find all top-level managers (employees who manage at least one person but have no manager themselves).',
            'Why does a CROSS JOIN not require an ON clause?',
            'What is the performance implication of a CROSS JOIN on large tables?',
            'Write a query to count how many direct reports each manager has.',
            'If the employees table has 10,000 rows and you accidentally forget the ON clause in a SELF JOIN, how many rows would the result have?\n\n---',
        ],
        "summary": 'Hierarchical data requires joining a table to itself. Today you mastered SELF JOINs to map manager-employee relations, and chained multiple joins in a single query.'
    },
    {
        "day": 12,
        "title": 'Subqueries',
        "db": 'ecommerce.db',
        "emoji": '🧠',
        "objective": 'Embed queries inside SELECT, WHERE, or FROM statements for multi-stage retrieval.',
        "sections": [{
            "num": 1,
            "title": 'Subqueries',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Subqueries.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                "Write a query using a subquery in WHERE to find all employees who earn more than the company's average salary. Show their <code>first_name</code>, <code>salary</code>, and the company average for comparison.",
                'Write a correlated subquery to find employees who earn more than the average salary of their own department.',
                'Using a subquery in FROM (derived table), compute the average salary per department, then filter to show only departments with an average salary above ₹65,000.',
                'Write a query using <code>EXISTS</code> to find all departments that have at least one employee earning above ₹90,000. Then write the equivalent query using <code>IN</code>. Compare the two approaches in a comment.',
                'Write a query using <code>NOT EXISTS</code> to find all departments that have NO employees. Compare this approach to the LEFT JOIN + IS NULL anti-join approach from Day 10.\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is a subquery? In what four locations can it appear?',
            'What is the difference between a correlated and a non-correlated subquery?',
            'Which runs first: the inner query or the outer query?',
            'What is a derived table (inline view)?',
            'What is a scalar subquery? What happens if it returns more than one row?',
            'What is the difference between <code>IN</code> and <code>EXISTS</code>?',
            'When is <code>EXISTS</code> preferred over <code>IN</code> for performance?',
            'Write a query to find employees who earn above the company average.',
            'What is the risk of using <code>NOT IN</code> when the subquery can return NULL values?',
            'Write a query using <code>NOT EXISTS</code> to find customers with no orders.',
            'What is a correlated subquery? Write an example.',
            'Can a subquery reference columns from the outer query?',
            'What is the difference between a subquery and a JOIN?',
            'When should you use a subquery vs. a JOIN?',
            'What is the performance impact of a correlated subquery on 1 million rows?',
            'Write a query to find the 2nd highest salary using a subquery (without LIMIT/OFFSET or window functions).',
            'What is the difference between a scalar subquery and a table-returning subquery?',
            'Can a subquery appear in the GROUP BY clause?',
            'Write a query to find all departments where the top earner is above ₹1,00,000.',
            'What is a subquery factoring (WITH clause)? (Preview of CTEs.)',
            'What does <code>SELECT 1</code> inside an EXISTS clause mean?',
            'Can you use ORDER BY inside a subquery? Does it have any effect?',
            'Write a query using a subquery to find the department with the most employees.',
            'Explain the concept of "query within a query" to a non-technical person.',
            'What is the difference between a view and a derived table (inline subquery)?\n\n---',
        ],
        "summary": 'Subqueries enable multi-stage logic. Today you mastered nested queries across SELECT, FROM, and WHERE clauses, including scalar subqueries, list subqueries (IN/NOT IN), and correlated subqueries (EXISTS/NOT EXISTS).'
    },
    {
        "day": 13,
        "title": 'CTEs (Common Table Expressions)',
        "db": 'ecommerce.db',
        "emoji": '🏗️',
        "objective": 'Define temporary, named result sets using Common Table Expressions (CTEs) for modular queries.',
        "sections": [{
            "num": 1,
            "title": 'CTEs (Common Table Expressions)',
            "subtitle": 'Concept Review',
            "theory": 'Learn about CTEs (Common Table Expressions).',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Rewrite this subquery using a CTE to improve readability:\n``<code>sql\nSELECT e.first_name, e.salary\nFROM employees e\nWHERE e.salary > (SELECT AVG(salary) FROM employees);\n</code>``',
                'Write a multi-CTE query that first computes the department-wise average salary, then identifies "premium departments" (avg > ₹75,000), then shows all employees from those premium departments along with their department\'s average.',
                "Write a recursive CTE to traverse the employee hierarchy starting from the CEO (the employee with <code>manager_id IS NULL</code>). Display each employee's name and their level in the org chart (CEO = Level 1, direct reports = Level 2, etc.).",
                "Using a CTE, compute the monthly revenue for 2024. Then, in the outer query, show each month, its revenue, and whether it is 'Above Average', 'Below Average', or 'Average' compared to the annual monthly average.",
                'Use two chained CTEs to: (1) find the top 5 sales reps by total order value, (2) then look up their employee details (name, department) from the employees table. Display the final ranked result.\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is a CTE and what keyword defines it?',
            'What is the difference between a CTE and a derived table (subquery in FROM)?',
            'Can a CTE be referenced multiple times in the same query?',
            'What is a recursive CTE? What are the two parts of a recursive CTE?',
            'What is the "anchor member" in a recursive CTE?',
            'What happens if a recursive CTE has no termination condition?',
            'Write a CTE query to find employees earning above the company average.',
            'What is the difference between <code>WITH RECURSIVE</code> in PostgreSQL and recursive CTEs in SQL Server?',
            'Can a CTE reference another CTE defined before it in the same WITH clause?',
            'What is an "optimization fence" in the context of CTEs in PostgreSQL?',
            'Write a CTE to traverse an organizational hierarchy 3 levels deep.',
            'When should you use a CTE vs. a VIEW?',
            'Can CTEs be used with INSERT, UPDATE, or DELETE statements?',
            'What is the lifecycle of a CTE — when does it get materialized?',
            'Write a multi-CTE query that computes running totals.',
            'What is <code>MATERIALIZED</code> vs. <code>NOT MATERIALIZED</code> in a CTE?',
            'What is the maximum depth of recursion in a recursive CTE (in PostgreSQL)?',
            'Can you put an ORDER BY inside a CTE? What is the effect?',
            'What are the advantages of CTEs over subqueries from a code maintenance perspective?',
            'Write a CTE that finds the top 3 departments by headcount.',
            'What is a "bill of materials" query and how does a recursive CTE solve it?',
            'How do you debug a multi-CTE query?',
            'What is the difference between <code>UNION</code> and <code>UNION ALL</code> inside a recursive CTE?',
            'Write a CTE that computes a 3-month rolling average of sales.',
            'When should you NOT use a CTE for performance reasons?\n\n---',
        ],
        "summary": 'CTEs modularize complex scripts. Today you mastered the WITH clause to create temporary named result sets, chained multiple CTEs sequentially, and studied the basics of recursive CTEs for hierarchical traversals.'
    },
    {
        "day": 14,
        "title": 'Window Functions Part 1 (Ranking)',
        "db": 'ecommerce.db',
        "emoji": '🔢',
        "objective": 'Calculate partition rankings, row numbers, and dense ranks using window functions.',
        "sections": [{
            "num": 1,
            "title": 'Window Functions Part 1 (Ranking)',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Window Functions Part 1 (Ranking).',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Use <code>ROW_NUMBER()</code> to assign a unique rank to each employee within their department based on salary (highest = 1). Show <code>first_name</code>, <code>department_id</code>, <code>salary</code>, and <code>row_num</code>.',
                'Use both <code>RANK()</code> and <code>DENSE_RANK()</code> on the entire employees table, ordered by salary descending. Show a case where they produce different results (ties). Display <code>first_name</code>, <code>salary</code>, <code>rank</code>, and <code>dense_rank</code> side by side.',
                'Using a CTE with <code>RANK()</code>, write a query to find the **top 2 highest-paid employees in each department**. (Remember: you cannot filter on window functions directly in WHERE — use a CTE.)',
                'Use <code>NTILE(5)</code> to divide all employees into 5 salary quintiles. Show <code>first_name</code>, <code>salary</code>, and <code>quintile</code>. Then count how many employees fall in each quintile.',
                'Using <code>ROW_NUMBER()</code> with <code>PARTITION BY</code> and <code>ORDER BY hire_date ASC</code>, find the **first employee hired in each department** (the most senior employee per dept). Display their name, department, and hire date.\n\n---',
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is a window function? How is it different from an aggregate function?',
            'What does the <code>OVER()</code> clause do?',
            'What is <code>PARTITION BY</code> in a window function?',
            'What is the difference between <code>ROW_NUMBER()</code>, <code>RANK()</code>, and <code>DENSE_RANK()</code>?',
            'When would you use <code>DENSE_RANK()</code> instead of <code>RANK()</code>?',
            'Write a query to rank employees by salary across the entire company.',
            'Write a query to rank employees by salary within their department.',
            'What is <code>NTILE(4)</code> and what does it produce?',
            "Why can't you filter on window function results directly in a WHERE clause?",
            'How do you get the top N per group using window functions?',
            'Write a query to find the 2nd highest salary per department.',
            'What happens with ties in <code>ROW_NUMBER()</code>?',
            'What is a window function "partition"?',
            'Can you use multiple window functions with different OVER() clauses in the same SELECT?',
            'What is the execution order of window functions in the SQL Order of Execution?',
            'Write a query to find employees in the top 25% of earners company-wide.',
            'Can you use <code>PARTITION BY</code> without <code>ORDER BY</code>?',
            'What is the difference between <code>RANK()</code> and PERCENT_RANK()`?',
            'Write a query to find the most recent order per customer.',
            'How does <code>ROW_NUMBER()</code> handle ties?',
            'What is the difference between <code>NTILE(4)</code> applied to 10 rows vs. 100 rows?',
            'Write a query to assign a "salary tier" (1=highest to 5=lowest) to employees using NTILE.',
            "Can you use aggregate functions inside a window function's OVER() clause?",
            'What is the performance cost of window functions on large tables?',
            'A business report needs the top 3 products by revenue per category. Write the SQL.\n\n---',
        ],
        "summary": 'Window functions perform analytical computations without collapsing rows. Today you mastered partition configuration using OVER(PARTITION BY) and ranking functions: ROW_NUMBER, RANK, DENSE_RANK, and NTILE.'
    },
    {
        "day": 15,
        "title": 'Window Functions Part 2 (Analytic)',
        "db": 'ecommerce.db',
        "emoji": '📈',
        "objective": 'Perform cumulative aggregations, running totals, and value offset analysis (LAG/LEAD).',
        "sections": [{
            "num": 1,
            "title": 'Window Functions Part 2 (Analytic)',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Window Functions Part 2 (Analytic).',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Using <code>LAG()</code>, compute the month-over-month sales change for each month in 2024. Show: <code>month</code>, <code>total_sales</code>, <code>prev_month_sales</code>, <code>sales_change</code>, and <code>pct_change</code> (as a percentage).',
                'Using <code>SUM() OVER()</code> with the <code>ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW</code> frame clause, compute the running cumulative total of order amounts ordered by <code>order_date</code>. Show <code>order_date</code>, <code>amount</code>, and <code>running_total</code>.',
                'Compute a 3-month rolling average of sales. Show months where the rolling average is higher than the actual sales for that month (hint: use a CTE).',
                "Using <code>FIRST_VALUE()</code> and <code>LAST_VALUE()</code>, find for each employee their department's highest and lowest salary. Make sure to use the correct window frame for <code>LAST_VALUE</code>.",
                "Write a query to show each customer's orders, and for each order, flag it as 'Increasing', 'Decreasing', or 'Same' based on whether the order amount is greater than, less than, or equal to the previous order by that same customer (use <code>LAG()</code> partitioned by <code>customer_id</code>).\n\n---",
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is <code>LAG()</code> and what is <code>LEAD()</code>? Give a practical business use case for each.',
            'What is the third parameter in <code>LAG(column, offset, default)</code> and when is it useful?',
            'What is a running total and how do you compute it in SQL?',
            'What is the window frame clause? What does <code>ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW</code> mean?',
            'What is the difference between <code>ROWS</code> and <code>RANGE</code> in a window frame?',
            'How do you compute a 7-day rolling average in SQL?',
            'What does <code>FIRST_VALUE()</code> return? What common mistake do people make with <code>LAST_VALUE()</code>?',
            'Why do you need <code>ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING</code> for <code>LAST_VALUE()</code>?',
            'What is <code>PERCENT_RANK()</code>? What is its range?',
            'What is <code>CUME_DIST()</code> and how is it different from <code>PERCENT_RANK()</code>?',
            'Write a query to compute month-over-month revenue growth.',
            'Write a query to compute year-to-date cumulative sales.',
            'What is the difference between a moving average and a cumulative sum?',
            'Can <code>LAG()</code> look more than 1 row back? Show the syntax.',
            "Write a query to find the difference between an employee's salary and the previous employee's salary when sorted by hire date.",
            'What happens to <code>LAG()</code> at the first row (no previous row)?',
            'Can you use <code>LAG()</code> with <code>PARTITION BY</code> to look at previous rows within a group?',
            'Write a SQL query to compute a running count of orders per customer.',
            'What is the purpose of <code>ROWS BETWEEN 6 PRECEDING AND CURRENT ROW</code>?',
            'How does window frame choice affect the result of <code>AVG()</code> in a window function?',
            'Write a query to flag rows where sales declined compared to the previous period.',
            'What is a "gap and islands" problem? (Advanced — how might LAG/LEAD help solve it?)',
            'How do window functions interact with CTEs for complex analytical queries?',
            'What is the difference between <code>SUM() OVER()</code> and <code>SUM() OVER(ORDER BY date)</code>?',
            'A dashboard needs: current month sales, previous month sales, and 3-month average in one row per month. Write the SQL.\n\n---',
        ],
        "summary": 'Analyzing timelines requires accessing offset rows. Today you mastered LAG and LEAD to compare rows chronologically, computed running aggregates, and configured moving average frame windows.'
    },
    {
        "day": 16,
        "title": 'String Functions',
        "db": 'ecommerce.db',
        "emoji": '🧹',
        "objective": 'Execute string cleanup, extraction, trim operations, and text pattern matching.',
        "sections": [{
            "num": 1,
            "title": 'String Functions',
            "subtitle": 'Concept Review',
            "theory": 'Learn about String Functions.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                "The <code>full_name</code> column has inconsistent casing and extra spaces (e.g., '  jOHN dOE  '). Write a query to clean it to proper title case with no extra spaces using <code>TRIM</code>, <code>LOWER</code>, and <code>INITCAP</code>.",
                'Extract the <code>username</code> (text before @) and <code>domain</code> (text after @) from the <code>email</code> column as separate columns. Use <code>SPLIT_PART</code> or <code>POSITION</code> + <code>SUBSTRING</code>.',
                "The <code>phone_number</code> column contains numbers in formats like '(91) 98765-43210', '91-98765-43210', '+91 98765 43210'. Write a query that standardizes all phone numbers to digits only (remove all non-numeric characters) using <code>REGEXP_REPLACE</code>.",
                "Write a query that finds all customers whose email domain is NOT 'gmail.com' or 'yahoo.com'. Use string functions to extract the domain and then filter.",
                "The <code>address</code> column stores city, state, and pincode separated by '|'. Write a query to extract each component into its own column: <code>city</code>, <code>state</code>, <code>pincode</code>. Then filter to show only customers in the state 'Maharashtra'.\n\n---",
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is the difference between <code>LENGTH()</code> and <code>CHAR_LENGTH()</code>?',
            'What does <code>TRIM()</code> do? How is it different from <code>LTRIM()</code> and <code>RTRIM()</code>?',
            'Write a query to convert all email addresses to lowercase.',
            'What does <code>CONCAT_WS()</code> do? How is it different from <code>||</code>?',
            'Write a query to extract the first 3 characters of a product code column.',
            'What is <code>LPAD()</code> and when would you use it in data analytics?',
            'How do you find the position of a substring within a string in SQL?',
            'Write a query to replace all spaces in a product name with underscores.',
            'What is <code>SPLIT_PART()</code>? Give an example of parsing a delimited column.',
            'How would you extract the year from a date stored as a VARCHAR column?',
            'Write a query to find all emails that are NOT in valid format (using LIKE or REGEXP).',
            'What is <code>INITCAP()</code>? Is it available in all databases?',
            'How do you remove all non-numeric characters from a phone number column?',
            'What is <code>REGEXP_REPLACE()</code>? Write an example.',
            'How would you check if a string contains a specific word?',
            'Write a query to count the number of words in a text column (hint: count spaces).',
            'What is the difference between <code>POSITION()</code> and <code>STRPOS()</code> in PostgreSQL?',
            "Write a query to generate an employee code as 'EMP' + a zero-padded employee_id (e.g., 'EMP00042').",
            'How do you reverse a string in SQL?',
            "What does <code>LEFT(email, POSITION('@' IN email) - 1)</code> compute?",
            'Write a query to find all customers whose name starts and ends with the same letter.',
            'What is string concatenation and what operator or function do you use for it?',
            'How would you parse a JSON-like string stored in a VARCHAR column?',
            "Write a query to identify email addresses with more than one '@' character.",
            "A data pipeline receives first_name and last_name in a single column as 'Last, First'. Write a query to split it into two separate columns.\n\n---",
        ],
        "summary": 'Text data is often messy. Today you mastered text manipulation and data cleaning functions: UPPER, LOWER, TRIM, REPLACE, SUBSTR, and INSTR to standardize text columns.'
    },
    {
        "day": 17,
        "title": 'Date & Time Functions',
        "db": 'ecommerce.db',
        "emoji": '📅',
        "objective": 'Perform calendar calculations, timestamp differences, and extract time segments.',
        "sections": [{
            "num": 1,
            "title": 'Date & Time Functions',
            "subtitle": 'Concept Review',
            "theory": 'Learn about Date & Time Functions.',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                "Write a query to show each employee's <code>first_name</code>, <code>hire_date</code>, and <code>years_of_service</code> (number of complete years from hire_date to today). Sort by longest-serving first.",
                'Write a monthly revenue report for 2024: group <code>orders</code> by month using <code>DATE_TRUNC</code>, and show total <code>order_count</code> and <code>monthly_revenue</code> for each month. Sort chronologically.',
                'Write a query to find all orders where the shipping took more than 7 days (difference between <code>shipped_date</code> and <code>order_date</code>). Show <code>order_id</code>, <code>order_date</code>, <code>shipped_date</code>, and <code>days_to_ship</code>.',
                'Write a quarterly revenue report that groups revenue by quarter (Q1, Q2, Q3, Q4) for all years in the orders table. Use <code>EXTRACT(QUARTER ...)</code> and <code>EXTRACT(YEAR ...)</code>. Display <code>year</code>, <code>quarter</code>, and <code>quarterly_revenue</code>.',
                "Write a query to display orders from the last 90 days (dynamically calculated — not hardcoded). Format the <code>order_date</code> for display as 'DD Mon YYYY' (e.g., '15 Jun 2024') using <code>TO_CHAR</code>.\n\n---",
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is the difference between <code>DATE</code>, <code>TIMESTAMP</code>, and <code>TIMESTAMPTZ</code>?',
            'How do you get the current date in SQL? Does the syntax vary by database?',
            'What does <code>EXTRACT(MONTH FROM hire_date)</code> return?',
            "What does <code>DATE_TRUNC('month', order_date)</code> return?",
            'Write a query to calculate the number of days between two dates.',
            'What is the difference between <code>DATEDIFF</code> and date subtraction?',
            'Write a query to find all employees hired in Q3 2023.',
            'How do you add 30 days to a date in PostgreSQL? In MySQL?',
            'What does <code>AGE(date1, date2)</code> return in PostgreSQL?',
            'Write a query to group orders by week number.',
            'What is <code>EPOCH</code> in the context of <code>EXTRACT</code>?',
            "How do you format a date as 'Month YYYY' for reporting?",
            'Write a query to find all employees with more than 5 years of service.',
            'What is the difference between <code>NOW()</code> and <code>CURRENT_DATE</code>?',
            'How would you find the last day of the current month in SQL?',
            'Write a query to find orders placed on a Sunday.',
            'What is <code>DATE_FORMAT</code> and in which database is it used?',
            'How do you filter records for "last 30 days" dynamically (without hardcoding a date)?',
            'Write a query to find the busiest day of the week for orders.',
            'What is the ISO week number and how is it different from a calendar week?',
            'How do time zones affect TIMESTAMP queries? How do you handle them?',
            "Write a query to find all customers who haven't placed an order in the last 6 months.",
            'How would you compute a fiscal year quarter (if fiscal year starts in April)?',
            "What is the difference between <code>DATE_TRUNC('week', date)</code> and <code>DATE_TRUNC('isoweek', date)</code>?",
            'A business needs a report of "last 12 months of revenue, grouped by month". Write the complete SQL query.\n\n---',
        ],
        "summary": 'Time-series analysis is a core analyst skill. Today you mastered temporal math, date formatting (STRFTIME), and date arithmetic to compute signup intervals and cohorts.'
    },
    {
        "day": 18,
        "title": 'UNION, INTERSECT & EXCEPT (SET Operations)',
        "db": 'capstone_retail.db',
        "emoji": '🥞',
        "objective": 'Execute set theory operations using UNION, INTERSECT, and EXCEPT queries.',
        "sections": [{
            "num": 1,
            "title": 'UNION, INTERSECT & EXCEPT (SET Operations)',
            "subtitle": 'Concept Review',
            "theory": 'Learn about UNION, INTERSECT & EXCEPT (SET Operations).',
            "demo": 'SELECT * FROM sales LIMIT 5;',
            "cc": 'Concept Checks',
            "questions": [
                'Combine all orders from <code>orders_2023</code> and <code>orders_2024</code> into a single result set. Add a column <code>year</code> (2023 or 2024) to identify the source. Use <code>UNION ALL</code>. Then count total orders and revenue per year in the outer query using a CTE.',
                'Using <code>INTERSECT</code>, find all customers who placed orders in **both** 2023 and 2024. Display their <code>customer_id</code> and fetch their <code>name</code> from the customers table (use a CTE or subquery).',
                'Using <code>EXCEPT</code>, find all customers who placed orders in 2023 but NOT in 2024 (i.e., they churned). Display their <code>customer_id</code> and <code>name</code>.',
                "You are validating a data migration. The <code>source_employees</code> table should match <code>target_employees</code>. Write two queries: (1) records in source missing from target, (2) records in target not in source (using EXCEPT). Combine both results using UNION ALL and add a <code>direction</code> column ('Source Only', 'Target Only').",
                "Build a comprehensive report using <code>UNION ALL</code> that shows:\n- Row 1: Total employees from <code>active_employees</code>\n- Row 2: Total employees from <code>archived_employees</code>\n- Row 3: Grand total across both\n\nLabel each with a <code>category</code> column ('Active', 'Archived', 'Total'). Use ROLLUP or UNION ALL with a summary row.\n\n---",
            ]
        }],
        "tasks": [],
        "interviews": [
            'What is a set operation in SQL? Name the three main set operations.',
            'What is the difference between <code>UNION</code> and <code>UNION ALL</code>?',
            'When should you use <code>UNION ALL</code> instead of <code>UNION</code> for performance?',
            'What are the three rules that all set operations must follow?',
            'What is <code>INTERSECT</code> and what does it return?',
            'What is <code>EXCEPT</code> and what is its Oracle equivalent?',
            'Write a query to find customers who ordered in 2023 but NOT in 2024 using EXCEPT.',
            'Write a query to find customers who ordered in BOTH 2023 AND 2024 using INTERSECT.',
            'What is the difference between UNION (vertical combine) and JOIN (horizontal combine)?',
            'Where does <code>ORDER BY</code> appear when using set operations?',
            'Can you use <code>ORDER BY</code> inside each individual SELECT of a UNION? Why not?',
            'Does <code>UNION</code> guarantee the order of results? Explain.',
            "What happens if the number of columns doesn't match in a UNION query?",
            'Can column data types differ in a UNION query? What does the database do?',
            'Write a query to consolidate sales from three regional tables into one summary report.',
            "How would you simulate <code>INTERSECT</code> in a database that doesn't support it (e.g., MySQL doesn't support INTERSECT directly)?",
            'How would you simulate <code>EXCEPT</code> using a JOIN?',
            'What is the difference between <code>EXCEPT</code> and <code>NOT EXISTS</code>/<code>NOT IN</code>?',
            'Can you UNION more than two queries?',
            "Write a query that uses UNION ALL to create a year-over-year comparison with a 'Year' label column.",
            'When would you use <code>EXCEPT</code> over LEFT JOIN anti-join pattern?',
            'What is the performance impact of <code>UNION</code> vs. <code>UNION ALL</code> on large result sets?',
            'Write a query to identify data quality issues: rows that exist in a source table but are missing from a target table after a data migration.',
            'Can set operations be combined with GROUP BY, HAVING, or window functions?',
            'A report requires combining employee data from 5 different subsidiary companies, all with the same schema. Which set operation would you use and why? Write the query structure.\n\n---',
        ],
        "summary": 'Set operations combine query result sets. Today you mastered UNION (deduplicated), UNION ALL (retained duplicates), INTERSECT (common rows), and EXCEPT (subtracted rows) to perform advanced comparative queries.'
    },
]
